### ISSUE TITLE
crypto in base.py case insensitive导致ImportError: cannot import name BaseCrypto

### ISSUE THREAD

**Issue by denny4nl** [doraemonext/wechat-python-sdk#101]
当外部使用from wechat_sdk import WechatConf时，
调用关系如下：
from wechat_sdk.core.conf import WechatConf  ->
from wechat_sdk.lib.crypto import BasicCrypto ->
from wechat_sdk.lib.crypto.base import BaseCrypto ->
from Crypto.Cipher import AES
此时会去lib/crypto/Crypto.py中import AES （当前文件名与python Crypto同名），导致import时互相依赖。
可以将lib/crypto/crypto.py修改为 lib/crypto/cryptos.py,
同时修改core/conf.py line 7修改为from wechat_sdk.lib.crypto.cryptos import BasicCrypto,
删除原来生成的lib/crypto/crypto.pyc，问题解决。

**Comment by doraemonext** [comment]
不太清楚何时会出现此种错误？能否将系统平台，错误提示贴出来看一下？我这里没有复现出该错误。

看样子是因为系统不区分文件名大小写导致，将会把 crypto.py 更新为 cryptos.py
