### ISSUE TITLE
维护access_token两种单机方式的区别？

### ISSUE THREAD

**Issue by DengKe1994** [doraemonext/wechat-python-sdk#103]
能否解释下方式1和2的区别，在我来看差别不大，都需要：
- 读取access_token
- 判断是否首次获取（无access_token）
- 使用access_token（或none）和expire_time（或none）构造实例
- ...

**Comment by WXiaoming** [comment]
方式二需要使用者手动维护 access_token，每次 get 时判断 access_token 的 TTL，若过期则重新向微信请求获取并更新内存及缓存（如果有）中的值。而方式一则不需要

**Comment by evilxyz** [comment]
实例化完成后（首次实例化两个参数均使用 None），你需要在该实例有效期内的任意时刻调用 .get_access_token() 方法获得自动维护过的新的 access_token 和 access_token_expires_at 值，然后将他们用你自己的方式（磁盘文件/数据库/缓存）进行保存，方便下次实例化的时候传入。

**Comment by evilxyz** [comment]
实例化完成后（首次实例化两个参数均使用 None），你需要在该实例有效期内的任意时刻调用 .get_access_token() 方法获得自动维护过的新的 access_token 和 access_token_expires_at 值，然后将他们用你自己的方式（磁盘文件/数据库/缓存）进行保存，方便下次实例化的时候传入。

对方式1有几个问题不理解
1. 我需要自行去获取access_token和access_token_expires_at的值吗?
2. 第一次调用需要怎么调用? 
3. 方式1会自动维护access_token吗? 还是需要我手动调用expires过期时间 ?

**Comment by DengKe1994** [comment]
看了看他的代码，才明白：
* @shijn 第二种方法，不需要维护过期时间，看下`WechatConf`类中的`access_token`属性方法，它会判断过期时间的，你只需要完成存储的事情。
* 我看到`WechatConf`类中的`get_access_token`方法，有一句注释**仅为兼容 v0.6.0 以前版本使用, 自行维护 access_token 请使用 access_token_setfunc 和 access_token_getfunc 进行操作**。豁然开朗，第二种设计明显比第一种高明，而第一种是向下兼容用的。 @doraemonext 如果只是兼容用的，建议在文档里特意说明下。

**Comment by DengKe1994** [comment]
@evilxyz 建议用方式2，效果一样，更容易理解，作者代码中说方式1只是为了保持向下兼容。
