### ISSUE TITLE
Python 3下加密模式有些Bug

### ISSUE THREAD

**Issue by DelightRun** [doraemonext/wechat-python-sdk#105]
Python 3下使用加密模式会有很多bug，有一部分bug是腾讯官方那个加密算法代码的。

**Bug主要成因：**Python 3下`str`对象无法直接与`bytes`对象进行相加，Python 2下是可以的。

我在我的fork上进行了修改，实测可用，但是不知道是否会导致Python 2下不兼容，所以还需要进一步测试。

[我的fork](https://github.com/DelightRun/wechat-python-sdk)

**Comment by doraemonext** [comment]
非常感谢，测试中

**Comment by DelightRun** [comment]
@doraemonext 我还在我的项目中增加了网页授权相关API（文档也写了），但是没测试。
主要是最近做项目在用本SDK，发现很多功能缺失，所以在修修改改

**Comment by DelightRun** [comment]
@doraemonext 我看了最新的修改，除了`letters`改为`ascii_letters`外应该还有个问题：

```python
 text = self.get_random_str() + struct.pack("I", socket.htonl(len(text))) + to_binary(text) + appid
```

这一行在Python 3下类型是`str +bytes + bytes + bytes`，需要将`get_random_str()`函数的结果同同样转换文`bytes`类型
