### ISSUE TITLE
关于线程安全

### ISSUE THREAD

**Issue by Jay54520** [doraemonext/wechat-python-sdk#110]
比如说，我这里类实例化的参数都是一样的，那么我可以在所有其他代码中引入实例化之后的 wechat而不是每次都再重新实例化出一个实例（wechat2, wechat3 ....）。
（因为我之前使用 Pymysql 遇到过这样的问题，需要为每个线程创建一个连接，不能共享）

``` python
conf = WechatConf(
    token=settings.WECHAT_TOKEN,
    appid=settings.WECHAT_APPID,
    appsecret=settings.WECHAT_APPSECRET,
    encrypt_mode='safe', 
    encoding_aes_key=settings.WECHAT_AESKEY,
    access_token_getfunc=get_access_token_function,
)
wechat = WechatBasic(conf=conf)  # 我现在是都用这个 wechat，没有再实例化别的 wechat 实例
```

**Comment by weizengquan** [comment]
同问。看源码，parse_data函数是直接将message等结果写在wechat的实例里了。那么假如这个时候下一个request来了，是否会修改同一个wechat实例？  总的来说，就是想问， wechat的实例操作，究竟是应该放在路由处理函数外面，全局一个，还是说应该放在request的处理函数里面？

**Comment by lvyaojia** [comment]
看具体代码实现，是线程不安全的。
