### ISSUE TITLE
使用StringIO作为上传多媒体的File-Object的时候，会返回类型错误

### ISSUE THREAD

**Issue by dingyaguang117** [doraemonext/wechat-python-sdk#12]
上传voice的时候，磁盘上的文件名为如果不为amr后缀 也是会报错(看后缀可能MP3也可以)。

感觉是少了Content-Type和filename
http://docs.python-requests.org/en/latest/user/quickstart/#post-a-multipart-encoded-file

Content-Type用微信的测试工具看了一下
image应该是：image/jpeg
voice应该是：voice/amr

**Comment by doraemonext** [comment]
非常感谢您的反馈，已经修正了该问题并更新版本至v0.5.2，具体用法请参见文档 :-)

如果仍然有Bug请继续反馈 :ghost:
