### ISSUE TITLE
don't lock requests version in setup.py

### ISSUE THREAD

**Issue by ilovenwd** [doraemonext/wechat-python-sdk#15]
requests==2.3.0

**Comment by doraemonext** [comment]
Thank you for your advice. I'm testing all the code in the new version of requests(2.6.0), and if there is no errors, I will unlock it.

**Comment by ilovenwd** [comment]
Lock in requirements.txt is ok, but should not in setup.py (when it's used as a library, It's very easy to conflict)

I use this
```
install_requires=map(lambda x: x.replace('==', '>='), open("requirements.txt").readlines()),
```

**Comment by mozillazg** [comment]
+1 for don't lock requests version

**Comment by doraemonext** [comment]
Already fixed.
