### ISSUE TITLE
素材管理可否分为临时素材和永久素材

### ISSUE THREAD

**Issue by KururuSouchou** [doraemonext/wechat-python-sdk#17]
例如在upload_media 和 download_media 方法新增一个参数，以判断是临时素材还是永久素材，并根据此参数决定所请求的url

**Comment by doraemonext** [comment]
将会在近几日更新 :)

**Comment by DeoLeung** [comment]
any update on this one?
also:
https://github.com/doraemonext/wechat-python-sdk/blob/develop/wechat_sdk/basic.py#L391

you check the extension by lower them, however at the end you call the ext dictionary without the action, this will cause KeyError

to be consistent, might move ext up and check by ' not in ext.keys()'
