### ISSUE TITLE
关于非官方接口中fakeid获取的方法

### ISSUE THREAD

**Issue by cmLighters** [doraemonext/wechat-python-sdk#25]
你好,我想问下非官方接口中发消息的用户的fakeid是怎么获取的?

**Comment by doraemonext** [comment]
http://wechat-python-sdk.readthedocs.org/zh_CN/latest/ext.html#wechat_sdk.ext.WechatExt.get_message_list

返回内容中由用户的fakeid

**Comment by cmLighters** [comment]
谢谢你的回答
