### ISSUE TITLE
支持 网页授权获取用户基本信息

### ISSUE THREAD

**Issue by stableShip** [doraemonext/wechat-python-sdk#30]
微信的[网页授权获取用户基本信息接口](http://mp.weixin.qq.com/wiki/17/c0f37d5704f0b64713d5d2c37b468d75.html)使用获取用户信息的,accesstoken的url和现在库里面的不同,是否添加sns的支持??

**Comment by yijingping** [comment]
问了作者，说他的代码已经写了，但是没有更新到github上来。如果你要使用，可以先用这个版本，亲测通过：https://github.com/bowenpay/wechat-python-sdk/releases/tag/v0.5.81

**Comment by stableShip** [comment]
谢了
