### ISSUE TITLE
python3下的编码格式问题

### ISSUE THREAD

**Issue by norrix** [doraemonext/wechat-python-sdk#38]
不知道作者在python3下的测试做的怎么样了，我在python3下使用遇到的主要问题还是编码格式的问题：
```python
type(u'abc') == unicode # python2
type(b'abc') == str     # python2
type(u'abc') == str     # python3
type(b'abc') == bytes   # python3
```
所以在一些编码判断和转码的地方都要做修改，比如WechatBasic.parse_data()和WechatBasic._transcoding()...

**Comment by hbrls** [comment]
看下 #36，也可以试一下我的 [fork](https://github.com/hbrls/wechat-python-sdk)，假如也能解决你的问题就 +1。

我也是想改尽量少的代码来解决这个问题，以免对原代码造成不好的影响，大家帮忙当小白鼠测试一下。

**Comment by norrix** [comment]
好的，其实问题也不是很大，我自己已经改好了…不过还是谢谢啦
