### ISSUE TITLE
generate_jsapi_signature 方法中，不需要去强制刷新 access_token

### ISSUE THREAD

**Issue by paicha** [doraemonext/wechat-python-sdk#43]
https://github.com/doraemonext/wechat-python-sdk/blob/master/wechat_sdk/basic.py#L289

这里直接使用 access_token 就可以了，本来 access_token 就会去判断刷新。

**Comment by JohnnyZhao** [comment]
嗯，这行可以去掉了

**Comment by paicha** [comment]
@JohnnyZhao #44 还请麻烦在 pypi 更新下。
