### ISSUE TITLE
希望尽快开发群发接口

### ISSUE THREAD

**Issue by weaming** [doraemonext/wechat-python-sdk#62]

**Comment by weaming** [comment]
算了，用 wechatpy

**Comment by kakalong001** [comment]
谢谢楼上，我安装的时候遇到了“ 'gbk' codec can't decode byte 0xae ”的问题，看到有人在这里提问了可是没人理，那我也转去wechatpy好了。

**Comment by weaming** [comment]
interesting

**Comment by gaoyuqi** [comment]
程序员更多是分享，老是等着要，还有抱怨情绪，。。。不好玩
