### ISSUE TITLE
间接性的出现错误OfficialAPIError: 40001

### ISSUE THREAD

**Issue by dragon-along** [doraemonext/wechat-python-sdk#70]
File "/home/wechat_sdk/basic.py", line 883, in _check_official_error
raise OfficialAPIError("{}: {}".format(json_data["errcode"], json_data["errmsg"]))
OfficialAPIError: 40001: invalid credential, access_token is invalid or not latest hint: [9.ZaUa0975vr21]

自从升级sdk后，间接性的出现40001错误，请问如何解决？

**Comment by yarving** [comment]
@dragon-along 你查看下接口权限的获取access_token是不是被消耗完了。

**Comment by doraemonext** [comment]
可能是 access token 维护问题，参考 [http://wechat-python-sdk.com/quickstart/wechatconf/](http://wechat-python-sdk.com/quickstart/wechatconf/)。

如果还是有问题，希望能提供更详细的日志信息。

**Comment by sunsongxp** [comment]
这个问题可能是因为你部署的时候，起了多个进程，每个进程都去微信的服务器获取一次access_token，只有最后一个获取到的access_token才有效，比如，如果你用gunicorn去启django，并设置4个进程，那么你会发现，每上传4个图片可能只有一个成功，其它都失败。我就遇到这个问题了。

`access_token是公众号的全局唯一接口调用凭据，公众号调用各接口时都需使用access_token。开发者需要进行妥善保存。access_token的存储至少要保留512个字符空间。access_token的有效期目前为2个小时，需定时刷新，重复获取将导致上次获取的access_token失效。`
