### ISSUE TITLE
AES加密模式下, 回复文本信息错误

### ISSUE THREAD

**Issue by hxer** [doraemonext/wechat-python-sdk#80]
场景：用户发送任意文本， 服务器原样返回
环境：python 2.7.11 + Flask

在加密模式下， 发送字符或数字，回复正确，发送中文时，出现错误：该公众号暂时无法提供服务，请稍后再试

部分测试代码如下：

content = u'你好'
content = content.decode('utf-8') if not isinstance(content, unicode) else content
return wechat.response_text(content)

当使用明文模式时， 发送中文，回复正常

**Comment by skyduy** [comment]
我这边也是

**Comment by zengbo** [comment]
这个问题是 utf8 字符集造成的。见代码 wechat_sdk/lib/crypto/base.py  32 行
len(text) 在计算utf8长度的时候，一个中文算一个长度，但是进行加密的时候，其实一个中文算3个字符长度，微信服务器进行解密获取后面的appid的时候失败了。
我的做法是把 len(text) 改成 len(text.encode('utf-8'))
