### ISSUE TITLE
支持微信企业号

### ISSUE THREAD

**Issue by suqi** [doraemonext/wechat-python-sdk#87]
请问 @doraemonext  是否有计划增加对微信企业号的支持？

我看到wechatpy已经支持了企业号，但是个人感觉wechat-python-sdk的设计和使用上比wechatpy优雅很多，所以希望做企业号也能继续沿用wechat-python-sdk的风格。

谢谢！

**Comment by yuzhiquan** [comment]
不知道是否已排期支持企业号？
