### ISSUE TITLE
关于WechatRequest类request方法的一点疑问

### ISSUE THREAD

**Issue by cheeringsoul** [doraemonext/wechat-python-sdk#92]
def request(self, method, url, access_token=None, **kwargs):
        """
        向微信服务器发送请求
        :param method: 请求方法
        :param url: 请求地址
        :param access_token: access token 值, 如果初始化时传入 conf 会自动获取, 如果没有传入则请提供此值
        :param kwargs: 附加数据
        :return: 微信服务器响应的 JSON 数据
        """
        access_token = self.__conf.access_token if self.__conf is not None else access_token
        if "params" not in kwargs:
            kwargs["params"] = {
                "access_token": access_token
            }
        else:
            kwargs["params"]["access_token"] = access_token

        if isinstance(kwargs.get("data", ""), dict):
            body = json.dumps(kwargs["data"], ensure_ascii=False)
            body = body.encode('utf8')
            kwargs["data"] = body

        r = requests.request(
            method=method,
            url=url,
            **kwargs
        )
        r.raise_for_status()
        try:
            response_json = r.json()
        except ValueError:  # 非 JSON 数据
            return r

        headimgurl = response_json.get('headimgurl')
        if headimgurl:
            response_json['headimgurl'] = headimgurl.replace('\\', '')
        self._check_official_error(response_json)
        return response_json

其中： access_token = self.__conf.access_token if self.__conf is not None else access_token
不是应该为：access_token = self.__conf.access_token if self.__conf.access_token is not None else access_token 吗？

**Comment by doraemonext** [comment]
代码没有错误，此处的设计思路如下：

- 如果 `__init__` 中传入了 `conf`，那么**一定**使用该 `conf` 去获取 access_token；
- 如果 `__init__` 没有传入，那么使用参数进行传入。

不会因为传入了 `conf` 但其 access_token 获取不到而选择参数进行传入，保证了 access_token 的有效性仅通过 `WechatConf` 进行控制。
