### ISSUE TITLE
django+mod_wsgi+apache 搭环境时引用包wechat的时候有问题

### ISSUE THREAD

**Issue by yolowang** [doraemonext/wechat-python-sdk#96]
我搭环境使用django，mod_wsgi，apache,在我引用from wechat_sdk import WechatBasic时访问页面时异常请求丢弃，不引用后页面正常，请教下会是什么问题？

**Comment by Rithard** [comment]
是不是源码没有在同一目录引起的错误？报 的是什么错误？

2016-06-11 14:00 GMT+08:00 yolowang <notifications@github.com>:

**Comment by yolowang** [comment]
没有报任何错，就是页面上啥都没有

**Comment by doraemonext** [comment]
请提供更详细一些的信息？比如各组件版本，Error具体信息，以及具体的出错代码
