### ISSUE TITLE
SAE支持

### ISSUE THREAD

**Issue by px200** [doraemonext/wechat-python-sdk#97]
这个module是需要PyCrypto 2.6.1, 但是SAE只支持2.6， 而且如果自己添加模块的话，仅支持运行纯Python的应用，不能动态加载C扩展，即.so，.dll等格式的模块不能使用， 导致一直出现 ImportError: cannot import name _AES， 因为缺少相应的dll模块，有什么解决方法吗？

**Comment by YuTingLiu** [comment]
直接使用SAE的即可，见预装的版本PyCrypto，文档见：https://www.sinacloud.com/doc/sae/python/runtime.html#shi-yong-yu-zhuang-mo-kuai

**Comment by Leonard-Peng** [comment]
在 `config.yaml` 中如你所说使用预装的版本，仍然报错 `ImportError: cannot import name _AES`：

```
libraries:
- name: PyCrypto
  version: "2.6"
```

请问有什么解决方法吗？
