### ISSUE TITLE
文档有误，模板消息关键词应为 "keyword1", "keyword2"...

### ISSUE THREAD

**Issue by lvyaojia** [doraemonext/wechat-python-sdk#98]
[发送模板消息文档](http://wechat-python-sdk.com/official/message/#_18)所写的 "keynote1", "keynote2" 应为 "keyword1", "keyword2", 此为微信公众号平台文档的错误，可参考 [模板审核标准](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433751288&token=&lang=zh_CN)  或具体的模板内容

微信开发者文档中的 [发送模板消息](https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433751277&token=&lang=zh_CN) 使用了 “keynote1"， "keynote2"  有误， 已联系微信开发者平台进行修改。

**Comment by doraemonext** [comment]
感谢反馈，已经更正。
